name: hello world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        uses: actions/checkout@v4
      - name: print html file
        run: cat test.html
        
         
